<?php
class AdminModalception extends WireData implements Module {

	public static function getModuleInfo() {

		return array(
			'title' => 'Modalception',
			'version' => '1.0.1',
			'summary' => "Improves usability of ProcessWire's modal dialog/popup windows when opened from within another modal window",
			'author' => 'Mike Spooner (thetuningspoon)',
			'href' => 'http://www.solutioninnovators.com',
			'singular' => true,
			'autoload' => 'template=admin',
			'icon' => 'dot-circle-o',
		);
	}

	public function init() {
		$this->config->scripts->add($this->config->urls->AdminModalception . "AdminModalception.js");
		$this->config->styles->add($this->config->urls->AdminModalception . "AdminModalception.css");
	}
}